version: "3.9"

services:
  api:
    build: ./src/MeuApi
    container_name: minha-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Host=db;Port=5432;Database=meu_db;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meu_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
